### PR TITLE
restructure results docs

### PR DESCRIPTION
**Pull request by geraintpalmer**
+ Remove all references to writing to file
+ Rename Output Data -> Results
+ More verbose Results docs, with examples

### CODE REVIEW

**Comment by geraintpalmer** [comment]
@drvinceknight Would you mind taking a look at this quick change?

**Comment by geraintpalmer** [comment]
@drvinceknight Doctests failing on Travis and Appveyor due to accuracy

```
File "./docs/Basics/results.rst", line 84, in results.rst
Failed example:
    service1
Expected:
    [0.05654464252280805, 0.13221434586351577, 0.12755938969775005, 0.10152545197095494, 0.1974548307228372]
Got:
    [0.056544642522808, 0.13221434586351588, 0.12755938969775005, 0.10152545197095494, 0.19745483072283718]
```

I don't want to put `round` around everything, as it loses readability. Any solution to this? Can I get Travis and Appveyor to skip these tests but not skip them locally? Or vice-versa?

**Comment by drvinceknight** [comment]
@geraintpalmer you can use `...` as a a character for "stuff goes here" so you'd have:

```
[0.056..., 0.132..., 0.127..., 0.1015..., 0.197...]
```

Which actually makes your docs slightly tidier too.

You need to tell your doctest runner to allow it first:

Include ability to use `Ellipsis` in doctests:

https://github.com/Axelrod-Python/Axelrod/blob/master/doctests.py#L14

Then use `...` in doctests:

Search for `results.eigenjesus_rating` here: https://github.com/Axelrod-Python/Axelrod/blob/master/docs/tutorials/getting_started/tournament_results.rst

You can test it locally first of course.

**Comment by drvinceknight** [comment]
> @drvinceknight Would you mind taking a look at this quick change?

Looks great to me. This is how I'd suggest each "how-to" be structured :) :+1:

**Pull request merged**
